### ISSUE TITLE
Consider moving under Gfx?

### ISSUE THREAD

**Issue by kvark** [gfx-rs/genmesh#17]
The recent rust breakage showed how `genmesh` could be a weak link of the ecosystem. gfx-rs breaks on it, glium does as well. We'd have to temporarily avoid using `genmesh` for the time of your absence. Perhaps, share some push access, or even move the repo under Gfx or PistonDevelopers?
Personally, I'd like to see `gfx-rs/mesh_gen` ;)

**Comment by csherratt** [comment]
@bvssvni do you think this makes more sense under `gfx` or under `Piston`?

**Comment by bvssvni** [comment]
@csherratt People who work on the projects under PistonDevelopers got the power to direct the project toward their personal goals. If you move it under Piston, it might happen more people contribute, but you also have to give them power relative to how much they work on it. That's the deal.

**Comment by csherratt** [comment]
With https://github.com/gfx-rs/gfx-rs/issues/726 I think I would like to move this under `gfx`. My original apprehension was that there was a the feud between `gfx-rs` and `glium` and I didn't want to be forced to take sides.

**Comment by kvark** [comment]
@csherratt what changed since then? Glium has even more presence now than ever.

I do support the move though, definitely :+1:

**Comment by bvssvni** [comment]
It is welcome under PistonDevelopers as well, but I don't mind it being under Gfx. Piston has no strict policy on license, but since you want Apache 2.0 and MIT is commonly used under Piston, then I would think dual licensing could be good. However, it is entirely up to you and don't think you should be that concerned about feuds. Think of what you want!

**Comment by csherratt** [comment]
This has been moved under gfx-rs.

@kvark gfx-rs has expanded beyond just being a low level graphics api where it began. I feel that now that gfx-rs is expanding upwards this utility library does not seem out of place with the ecosystem (it would have made sense in piston too). The choice of gfx-rs over piston is mostly because I felt it matches the gfx-rs ecosystem a bit better.

**Comment by kvark** [comment]
@csherratt wooohoo! I guess we can start integrating it better with gfx ecosystem now. We could still have a neutral layer underneath for folks using raw gl-rs or glium.
